apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secret
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.app.secret.dbPassword | b64enc | quote }}
  {{- if .Values.app.secret.redisPassword }}
  REDIS_PASSWORD: {{ .Values.app.secret.redisPassword | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ .Values.app.secret.jwtSecret | b64enc | quote }}
  {{- if .Values.app.secret.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.app.secret.googleClientSecret | b64enc | quote }}
  {{- end }}
  ADMIN_PASSWORD: {{ .Values.app.secret.adminPassword | b64enc | quote }}
  ADMIN_ENCRYPTED_PRIVATE_KEY: {{ .Values.app.secret.adminEncryptedPrivateKey | b64enc | quote }}
