replicaCount: 1

image:
  repository: ghcr.io/nguyentukien/secweb
  pullPolicy: IfNotPresent
  tag: "latest" # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

app:
  config:
    SPRING_DOCKER_COMPOSE_ENABLED: false
    SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mini_messenger?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_JPA_HIBERNATE_DDL_AUTO: update    

    SPRING_DATA_REDIS_URL: "[REDIS_URL]"
    SPRING_DATA_REDIS_TIMEOUT: 3s
    SPRING_DATA_REDIS_REPOSITORY_ENABLED: false

    APP_JWT_SECRET: "[JWT_SECRET]"
    APP_JWT_ACCESS_TOKEN_TTL_MINUTES: 15
    APP_JWT_REFRESH_TOKEN_TTL_DAYS: 30

    APP_GOOGLE_CLIENT_ID: "[GOOGLE_CLIENT_ID]"
    APP_GOOGLE_ALLOWED_AUDIENCES: "[GOOGLE_CLIENT_ID]"

    APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"

    APP_BOOTSTRAP_ADMIN_ENABLED: true
    APP_BOOTSTRAP_ADMIN_USERNAME: admin
    APP_BOOTSTRAP_ADMIN_EMAIL: "[EMAIL_ADDRESS]"
    APP_BOOTSTRAP_ADMIN_MASTER_KEY_PUBLIC_KEY: "[PUBLIC_KEY]"
    APP_BOOTSTRAP_ADMIN_MASTER_KEY_PRIVATE_KEY_IV: "[BASE64_ENCODED_IV]"
    APP_BOOTSTRAP_ADMIN_MASTER_KEY_PIN_SALT: "[PIN_SALT]"
    APP_BOOTSTRAP_ADMIN_MASTER_KEY_KDF_PARAMS: "{ \"algorithm\": \"PBKDF2\", \"iterations\": 100000, \"keyLength\": 256, \"digest\": \"SHA-256\", \"bootstrap\": true }"

    # CLOUDFLARE
    CLOUDFLARE_TUNNEL_TOKEN: "[CLOUDFLARE_TUNNEL_TOKEN]"
  secret:
    SPRING_DATASOURCE_PASSWORD: "[PASSWORD]"
    SPRING_DATA_REDIS_PASSWORD: "[PASSWORD]"
    APP_JWT_SECRET: "[ENCRYPTION_KEY]"
    APP_GOOGLE_CLIENT_SECRET: "[OAUTH_CLIENT_SECRET]"
    APP_BOOTSTRAP_ADMIN_PASSWORD: "[PASSWORD]"
    APP_BOOTSTRAP_ADMIN_MASTER_KEY_ENCRYPTED_PRIVATE_KEY: "[ENCRYPTED_PRIVATE_KEY]"
